import {
  CreditCase,
  CaseVerdict,
  AppealVerdict,
  BorrowerReputation,
  ReviewedCaseRecord,
  ProtocolStats,
} from '@/types/fiducia';

export const MOCK_CASES: CreditCase[] = [
  {
    case_id: '1',
    borrower: '0xA1b2C3d4E5f6A7B8C9D0E1F2A3B4C5D6E7F8A9B0',
    business_name: 'Sunrise Textile Co.',
    business_type: 'Online fashion marketplace',
    loan_amount_requested: 5000,
    loan_duration_months_requested: 12,
    loan_purpose: 'Inventory expansion ahead of festive season',
    business_age_months: 18,
    evidence_commitment: '0xabc123def456',
    evidence_schema_version: 'FIDUCIA_SANITISED_V1',
    status: 'REVIEWED',
    created_at: 1700000000,
    updated_at: 1700100000,
  },
  {
    case_id: '2',
    borrower: '0xB2C3D4E5F6A7B8C9D0E1F2A3B4C5D6E7F8A9B0C1',
    business_name: 'Kola Agri Supplies',
    business_type: 'Agricultural input distributor',
    loan_amount_requested: 8000,
    loan_duration_months_requested: 18,
    loan_purpose: 'Warehouse expansion and equipment',
    business_age_months: 36,
    evidence_commitment: '0xdef789ghi012',
    evidence_schema_version: 'FIDUCIA_SANITISED_V1',
    status: 'REVIEWED',
    created_at: 1700200000,
    updated_at: 1700300000,
  },
  {
    case_id: '3',
    borrower: '0xC3D4E5F6A7B8C9D0E1F2A3B4C5D6E7F8A9B0C1D2',
    business_name: 'Lagos Digital Hub',
    business_type: 'Tech training and services',
    loan_amount_requested: 12000,
    loan_duration_months_requested: 24,
    loan_purpose: 'Expand training facilities',
    business_age_months: 8,
    evidence_commitment: '0xghi345jkl678',
    evidence_schema_version: 'FIDUCIA_SANITISED_V1',
    status: 'REVIEWED',
    created_at: 1700400000,
    updated_at: 1700500000,
  },
  {
    case_id: '4',
    borrower: '0xD4E5F6A7B8C9D0E1F2A3B4C5D6E7F8A9B0C1D2E3',
    business_name: 'Adaeze Foods & Catering',
    business_type: 'Food service and catering',
    loan_amount_requested: 3500,
    loan_duration_months_requested: 9,
    loan_purpose: 'Kitchen upgrade and catering fleet',
    business_age_months: 28,
    evidence_commitment: '0xjkl901mno234',
    evidence_schema_version: 'FIDUCIA_SANITISED_V1',
    status: 'APPEAL_REVIEWED',
    created_at: 1700600000,
    updated_at: 1700800000,
  },
];

export const MOCK_VERDICTS: Record<string, CaseVerdict> = {
  '1': {
    case_id: '1',
    credit_score: 74,
    risk_level: 'low',
    decision: 'approve',
    confidence: 82,
    repayment_probability: 79,
    recommended_terms: {
      max_loan_amount: 5000,
      interest_rate: 9.5,
      loan_duration_months: 12,
      conditions: ['Maintain monthly revenue reports', 'Notify lender of major supplier changes'],
    },
    reasoning: [
      'Consistent positive cashflow across 5 of 6 months shows operational resilience.',
      'Requested loan amount is proportionate to demonstrated monthly revenue capacity.',
      'Business age of 18 months indicates early but established operational phase.',
      'Inventory expansion purpose is well-aligned with documented revenue seasonality.',
    ],
    risk_flags: ['Business still in early growth phase', 'Revenue shows seasonal dependency'],
    positive_signals: ['Positive cashflow trend', 'Clear loan purpose', 'Good supplier relationships'],
    reviewed_by_trigger: '0x0000000000000000000000000000000000000001',
  },
  '2': {
    case_id: '2',
    credit_score: 61,
    risk_level: 'medium',
    decision: 'conditional_approve',
    confidence: 71,
    repayment_probability: 65,
    recommended_terms: {
      max_loan_amount: 6000,
      interest_rate: 13.0,
      loan_duration_months: 18,
      conditions: [
        'Provide quarterly cashflow statements',
        'Loan amount capped at 6000',
        'Personal guarantee required',
      ],
    },
    reasoning: [
      'Revenue is substantial but shows moderate volatility across the review period.',
      'Warehouse expansion is a capital-intensive purpose with medium-term payback.',
      'Existing supplier debt reduces available repayment capacity somewhat.',
      'Strong reputation signals from market relationships mitigate some risk.',
    ],
    risk_flags: ['Existing supplier debt', 'Capital-intensive expansion purpose', 'Revenue volatility'],
    positive_signals: ['Established 3-year track record', 'Strong market relationships', 'Clear business purpose'],
    reviewed_by_trigger: '0x0000000000000000000000000000000000000001',
  },
  '3': {
    case_id: '3',
    credit_score: 34,
    risk_level: 'high',
    decision: 'reject',
    confidence: 78,
    repayment_probability: 38,
    recommended_terms: {
      max_loan_amount: 2000,
      interest_rate: 22.0,
      loan_duration_months: 12,
      conditions: ['Revisit after 12 months of stable revenue', 'Submit improved evidence of demand'],
    },
    reasoning: [
      'Business is only 8 months old which is insufficient track record for a 12,000 loan.',
      'Revenue figures are inconsistent and do not support the requested loan amount.',
      'Tech training sector shows high sensitivity to market conditions and competition.',
      'Repayment probability at current revenue levels is below acceptable threshold for approval.',
    ],
    risk_flags: ['Very young business (8 months)', 'Loan amount exceeds demonstrated revenue capacity', 'Sector volatility'],
    positive_signals: ['Growing sector', 'Clear facility expansion plan'],
    reviewed_by_trigger: '0x0000000000000000000000000000000000000001',
  },
  '4': {
    case_id: '4',
    credit_score: 58,
    risk_level: 'medium',
    decision: 'conditional_approve',
    confidence: 68,
    repayment_probability: 62,
    recommended_terms: {
      max_loan_amount: 3000,
      interest_rate: 14.5,
      loan_duration_months: 9,
      conditions: ['Limited to kitchen equipment only', 'Monthly revenue verification'],
    },
    reasoning: [
      'Food service business shows steady repeat client base and positive cashflow.',
      'Requested amount is reasonable for the stated kitchen upgrade purpose.',
      'Catering fleet addition adds risk but also revenue potential.',
      'Initial verdict: conditional approval with reduced amount.',
    ],
    risk_flags: ['Fleet purchase adds operational complexity', 'Seasonal demand patterns'],
    positive_signals: ['Steady repeat clientele', 'Positive cashflow history', 'Established 28-month track record'],
    reviewed_by_trigger: '0x0000000000000000000000000000000000000001',
  },
};

export const MOCK_APPEAL_VERDICTS: Record<string, AppealVerdict> = {
  '4': {
    case_id: '4',
    appeal_outcome: 'improve',
    revised_credit_score: 68,
    revised_risk_level: 'medium',
    revised_decision: 'approve',
    confidence: 74,
    reasoning: [
      'New evidence shows two additional long-term catering contracts signed post-review.',
      'Updated cashflow projections show improved repayment capacity.',
      'Revised decision: full approval at original requested amount is now justified.',
    ],
    changed_terms: {
      max_loan_amount: 3500,
      interest_rate: 12.0,
      loan_duration_months: 9,
      conditions: ['Maintain catering contract documentation', 'Quarterly revenue check-in'],
    },
  },
};

export const MOCK_REPUTATION: Record<string, BorrowerReputation> = {
  '0xA1b2C3d4E5f6A7B8C9D0E1F2A3B4C5D6E7F8A9B0': {
    borrower: '0xA1b2C3d4E5f6A7B8C9D0E1F2A3B4C5D6E7F8A9B0',
    total_reviewed_cases: 1,
    approved_count: 1,
    conditional_count: 0,
    rejected_count: 0,
    average_credit_score: 74,
    average_repayment_probability: 79,
    last_risk_level: 'low',
    last_decision: 'approve',
    last_reviewed_case_id: '1',
  },
  '0xB2C3D4E5F6A7B8C9D0E1F2A3B4C5D6E7F8A9B0C1': {
    borrower: '0xB2C3D4E5F6A7B8C9D0E1F2A3B4C5D6E7F8A9B0C1',
    total_reviewed_cases: 1,
    approved_count: 0,
    conditional_count: 1,
    rejected_count: 0,
    average_credit_score: 61,
    average_repayment_probability: 65,
    last_risk_level: 'medium',
    last_decision: 'conditional_approve',
    last_reviewed_case_id: '2',
  },
};

export const MOCK_REVIEWED_CASES: ReviewedCaseRecord[] = [
  { case: MOCK_CASES[0], verdict: MOCK_VERDICTS['1'], appeal_verdict: null },
  { case: MOCK_CASES[1], verdict: MOCK_VERDICTS['2'], appeal_verdict: null },
  { case: MOCK_CASES[2], verdict: MOCK_VERDICTS['3'], appeal_verdict: null },
  { case: MOCK_CASES[3], verdict: MOCK_VERDICTS['4'], appeal_verdict: MOCK_APPEAL_VERDICTS['4'] },
];

export const MOCK_PROTOCOL_STATS: ProtocolStats = {
  total_cases: 4,
  total_reviews: 4,
  total_appeals: 1,
  review_fee: 1000000000000000,
  paused: false,
  admin: '0xADMIN000000000000000000000000000000000001',
};
